name: CD - Continuous Deployment

on:
  workflow_run:
    workflows: ["CI - Continuous Integration"]
    types:
      - completed
    branches: [main]

  # Manual trigger for releases
  workflow_dispatch:
    inputs:
      force_deploy:
        description: "Force deployment even if CI failed"
        required: false
        default: false
        type: boolean

env:
  IMAGE_NAME: odysseus-job-tracker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate tags
        id: tags
        run: |
          VERSION="1.0.${{ github.run_number }}"
          echo "tags=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${VERSION},${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.tags.outputs.version }}
          name: v${{ steps.tags.outputs.version }}
          body: |
            Docker image: `${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.tags.outputs.version }}`

            ```bash
            docker run -p 8080:80 ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ```
          draft: false
          prerelease: false
